/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import utils.Validador;

/**
 *
 * @author caueg
 */
public class TelaCadastroVendaView extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroClientesView
     */
    public TelaCadastroVendaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalCadasVendas = new javax.swing.JPanel();
        pnlTituloCadasVendas = new javax.swing.JPanel();
        lblTituloCadasVendas = new javax.swing.JLabel();
        pnlInfoCadasVendas = new javax.swing.JPanel();
        lblIdVend = new javax.swing.JLabel();
        lblIdProdVend = new javax.swing.JLabel();
        lblCpfCliVend = new javax.swing.JLabel();
        lblDataVend = new javax.swing.JLabel();
        txtDataVend = new javax.swing.JFormattedTextField();
        lblValorUniVend = new javax.swing.JLabel();
        txtIdVend = new javax.swing.JTextField();
        txtIdProdVend = new javax.swing.JTextField();
        lblIdCliVend = new javax.swing.JLabel();
        txtIdCienteVend = new javax.swing.JTextField();
        txtCpfCliVend = new javax.swing.JFormattedTextField();
        lblQuantProdVend = new javax.swing.JLabel();
        txtQuantiadeProdVend = new javax.swing.JTextField();
        lblValorTotVend = new javax.swing.JLabel();
        btnAdicionarItens = new javax.swing.JButton();
        btnExcluirItes = new javax.swing.JButton();
        btnLimparItens = new javax.swing.JButton();
        lblValorUniProdVendAt = new javax.swing.JLabel();
        lblValorTotProdVendAt = new javax.swing.JLabel();
        btnFinalizaCompra = new javax.swing.JButton();
        pnlItesSacola = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensVend = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro de Venda");

        pnlPrincipalCadasVendas.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalCadasVendas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloCadasVendas.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloCadasVendas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloCadasVendas.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloCadasVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCadasVendas.setText("Cadastro de Venda");

        javax.swing.GroupLayout pnlTituloCadasVendasLayout = new javax.swing.GroupLayout(pnlTituloCadasVendas);
        pnlTituloCadasVendas.setLayout(pnlTituloCadasVendasLayout);
        pnlTituloCadasVendasLayout.setHorizontalGroup(
            pnlTituloCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloCadasVendasLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(lblTituloCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(306, 306, 306))
        );
        pnlTituloCadasVendasLayout.setVerticalGroup(
            pnlTituloCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloCadasVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInfoCadasVendas.setBackground(new java.awt.Color(0, 0, 0));

        lblIdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblIdVend.setText("ID Venda:");

        lblIdProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblIdProdVend.setText("*ID Produto:");

        lblCpfCliVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblCpfCliVend.setForeground(new java.awt.Color(204, 255, 204));
        lblCpfCliVend.setText("*CPF Cliente:");

        lblDataVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblDataVend.setForeground(new java.awt.Color(204, 255, 204));
        lblDataVend.setText("*Data:");

        txtDataVend.setBackground(new java.awt.Color(255, 255, 255));
        txtDataVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtDataVend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtDataVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblValorUniVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblValorUniVend.setForeground(new java.awt.Color(204, 255, 204));
        lblValorUniVend.setText("Valor unitário:");

        txtIdVend.setBackground(new java.awt.Color(255, 255, 255));
        txtIdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtIdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtIdProdVend.setBackground(new java.awt.Color(255, 255, 255));
        txtIdProdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdProdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtIdProdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblIdCliVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdCliVend.setForeground(new java.awt.Color(204, 255, 204));
        lblIdCliVend.setText("*ID Cliente:");

        txtIdCienteVend.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCienteVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdCienteVend.setForeground(new java.awt.Color(0, 0, 0));
        txtIdCienteVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtCpfCliVend.setBackground(new java.awt.Color(255, 255, 255));
        txtCpfCliVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtCpfCliVend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpfCliVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblQuantProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblQuantProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblQuantProdVend.setText("*Quantidade Produto:");

        txtQuantiadeProdVend.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantiadeProdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtQuantiadeProdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtQuantiadeProdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblValorTotVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblValorTotVend.setForeground(new java.awt.Color(204, 255, 204));
        lblValorTotVend.setText("Valor Total:");

        btnAdicionarItens.setBackground(new java.awt.Color(204, 255, 204));
        btnAdicionarItens.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnAdicionarItens.setForeground(new java.awt.Color(0, 0, 0));
        btnAdicionarItens.setText("Adicionar Item");
        btnAdicionarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItensActionPerformed(evt);
            }
        });

        btnExcluirItes.setBackground(new java.awt.Color(204, 255, 204));
        btnExcluirItes.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnExcluirItes.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirItes.setText("Excluir Item");
        btnExcluirItes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItesActionPerformed(evt);
            }
        });

        btnLimparItens.setBackground(new java.awt.Color(204, 255, 204));
        btnLimparItens.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnLimparItens.setForeground(new java.awt.Color(0, 0, 0));
        btnLimparItens.setText("Limpar");
        btnLimparItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparItensActionPerformed(evt);
            }
        });

        lblValorUniProdVendAt.setForeground(new java.awt.Color(204, 255, 204));
        lblValorUniProdVendAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorUniProdVendAt.setText("___________________");

        lblValorTotProdVendAt.setForeground(new java.awt.Color(204, 255, 204));
        lblValorTotProdVendAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotProdVendAt.setText("___________________");

        javax.swing.GroupLayout pnlInfoCadasVendasLayout = new javax.swing.GroupLayout(pnlInfoCadasVendas);
        pnlInfoCadasVendas.setLayout(pnlInfoCadasVendasLayout);
        pnlInfoCadasVendasLayout.setHorizontalGroup(
            pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                        .addComponent(lblCpfCliVend)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCpfCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                        .addComponent(lblIdCliVend)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdCienteVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(lblDataVend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionarItens)
                                    .addComponent(txtDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(174, 174, 174)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addComponent(lblIdProdVend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorUniVend)
                                    .addComponent(lblQuantProdVend))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuantiadeProdVend, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(lblValorUniProdVendAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(lblIdVend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(lblValorTotVend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addComponent(btnLimparItens, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(btnExcluirItes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValorTotProdVendAt))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        pnlInfoCadasVendasLayout.setVerticalGroup(
            pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdVend)
                    .addComponent(txtIdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCliVend)
                    .addComponent(txtIdCienteVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProdVend)
                    .addComponent(txtIdProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCliVend)
                    .addComponent(txtCpfCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantiadeProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantProdVend))
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorTotVend)
                            .addComponent(lblValorTotProdVendAt))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataVend)
                            .addComponent(lblValorUniVend)
                            .addComponent(lblValorUniProdVendAt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarItens)
                            .addComponent(btnLimparItens)
                            .addComponent(btnExcluirItes))
                        .addContainerGap())))
        );

        pnlInfoCadasVendasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCpfCliVend, txtDataVend, txtIdCienteVend});

        pnlInfoCadasVendasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblValorTotProdVendAt, lblValorUniProdVendAt, txtQuantiadeProdVend});

        btnFinalizaCompra.setBackground(new java.awt.Color(204, 255, 204));
        btnFinalizaCompra.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnFinalizaCompra.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizaCompra.setText("Finalizar compra");
        btnFinalizaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaCompraActionPerformed(evt);
            }
        });

        pnlItesSacola.setBackground(new java.awt.Color(0, 0, 0));
        pnlItesSacola.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens Adicionados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        pnlItesSacola.setForeground(new java.awt.Color(204, 255, 204));
        pnlItesSacola.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlItesSacola.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        tblItensVend.setBackground(new java.awt.Color(0, 0, 0));
        tblItensVend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "ID Produto", "CPF Cliente", "Quantidade Produto", "Data", "Valor Unitário", "Valor Total"
            }
        ));
        tblItensVend.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblItensVend);

        javax.swing.GroupLayout pnlItesSacolaLayout = new javax.swing.GroupLayout(pnlItesSacola);
        pnlItesSacola.setLayout(pnlItesSacolaLayout);
        pnlItesSacolaLayout.setHorizontalGroup(
            pnlItesSacolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItesSacolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlItesSacolaLayout.setVerticalGroup(
            pnlItesSacolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItesSacolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPrincipalCadasVendasLayout = new javax.swing.GroupLayout(pnlPrincipalCadasVendas);
        pnlPrincipalCadasVendas.setLayout(pnlPrincipalCadasVendasLayout);
        pnlPrincipalCadasVendasLayout.setHorizontalGroup(
            pnlPrincipalCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalCadasVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfoCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlItesSacola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCadasVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );
        pnlPrincipalCadasVendasLayout.setVerticalGroup(
            pnlPrincipalCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCadasVendasLayout.createSequentialGroup()
                .addComponent(pnlTituloCadasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoCadasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlItesSacola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnFinalizaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaCompraActionPerformed
        
    }//GEN-LAST:event_btnFinalizaCompraActionPerformed

    private void btnLimparItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparItensActionPerformed
            txtIdCienteVend.setText("");
            txtIdProdVend.setText("");
            txtCpfCliVend.setText("");
            txtQuantiadeProdVend.setText("");
            txtDataVend.setText("");
    }//GEN-LAST:event_btnLimparItensActionPerformed

    private void btnAdicionarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItensActionPerformed
        Validador validacao = new Validador();
        
        validacao.ValidarNumero(txtIdCienteVend);
        validacao.ValidarNumero(txtIdProdVend);
        validacao.ValidarCpf(txtCpfCliVend);
        validacao.ValidarNumero(txtQuantiadeProdVend);
        validacao.ValidarData(txtDataVend);
        
        if(validacao.hasErro()){
            JOptionPane.showMessageDialog(this, "Preencha corretamente os campos em vermelho");
        }
        
    }//GEN-LAST:event_btnAdicionarItensActionPerformed

    private void btnExcluirItesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirItesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItens;
    private javax.swing.JButton btnExcluirItes;
    private javax.swing.JButton btnFinalizaCompra;
    private javax.swing.JButton btnLimparItens;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpfCliVend;
    private javax.swing.JLabel lblDataVend;
    private javax.swing.JLabel lblIdCliVend;
    private javax.swing.JLabel lblIdProdVend;
    private javax.swing.JLabel lblIdVend;
    private javax.swing.JLabel lblQuantProdVend;
    private javax.swing.JLabel lblTituloCadasVendas;
    private javax.swing.JLabel lblValorTotProdVendAt;
    private javax.swing.JLabel lblValorTotVend;
    private javax.swing.JLabel lblValorUniProdVendAt;
    private javax.swing.JLabel lblValorUniVend;
    private javax.swing.JPanel pnlInfoCadasVendas;
    private javax.swing.JPanel pnlItesSacola;
    private javax.swing.JPanel pnlPrincipalCadasVendas;
    private javax.swing.JPanel pnlTituloCadasVendas;
    private javax.swing.JTable tblItensVend;
    private javax.swing.JFormattedTextField txtCpfCliVend;
    private javax.swing.JFormattedTextField txtDataVend;
    private javax.swing.JTextField txtIdCienteVend;
    private javax.swing.JTextField txtIdProdVend;
    private javax.swing.JTextField txtIdVend;
    private javax.swing.JTextField txtQuantiadeProdVend;
    // End of variables declaration//GEN-END:variables
}
