/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import utils.Validador;

/**
 *
 * @author caueg
 */
public class TelaAlteExclClientesView extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroClientesView
     */
    public TelaAlteExclClientesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalAltExcClientes = new javax.swing.JPanel();
        pnlTituloAltExcClientes = new javax.swing.JPanel();
        lblTituloAltExcClientes = new javax.swing.JLabel();
        btnAlterarClientes = new javax.swing.JButton();
        btnExcluirClientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAltExcClientes = new javax.swing.JTable();
        lblNomeConsCli = new javax.swing.JLabel();
        pnlInfoConsClientes = new javax.swing.JPanel();
        txtAltExcCidCli = new javax.swing.JTextField();
        lblAltExcTelCli = new javax.swing.JLabel();
        lblAltExcCepCli = new javax.swing.JLabel();
        lblAltExcLograCli = new javax.swing.JLabel();
        lblAltExcSexCli = new javax.swing.JLabel();
        txtAltExcNumCepCli = new javax.swing.JTextField();
        lblAltExcIdCli = new javax.swing.JLabel();
        lblAltExcNomeCli = new javax.swing.JLabel();
        txtAltExcCepCli = new javax.swing.JFormattedTextField();
        lblAltExcComplCli = new javax.swing.JLabel();
        txtAltExcEmailCli = new javax.swing.JTextField();
        lblAltExcNumCepCli = new javax.swing.JLabel();
        txtAltExcComplCli = new javax.swing.JTextField();
        lblAltExcECCli = new javax.swing.JLabel();
        txtAltExcLograCli = new javax.swing.JTextField();
        lblAltExcCidCli = new javax.swing.JLabel();
        txtAltExcTelCli = new javax.swing.JFormattedTextField();
        lblAltExcCpfCli = new javax.swing.JLabel();
        lblAltExcDataNascCli = new javax.swing.JLabel();
        txtAltExcNomeCli = new javax.swing.JTextField();
        lblAltExcEmailCli = new javax.swing.JLabel();
        lblAltExcIdCliAt = new javax.swing.JLabel();
        lblAltExcCpfCliAt = new javax.swing.JLabel();
        lblAltExcDataNasCliAt = new javax.swing.JLabel();
        cbbAltExcSexoCliAt = new javax.swing.JComboBox<>();
        cbbAltExcEstCivCliAt = new javax.swing.JComboBox<>();
        lblInfoAltExcClientes = new javax.swing.JLabel();
        btnConsutarClientes = new javax.swing.JButton();
        txtCpfCliCons = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Alteração e Exclusão de Clientes");
        setAlwaysOnTop(true);

        pnlPrincipalAltExcClientes.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalAltExcClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloAltExcClientes.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloAltExcClientes.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloAltExcClientes.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloAltExcClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAltExcClientes.setText("Alteração e Exclusão de Clientes");

        javax.swing.GroupLayout pnlTituloAltExcClientesLayout = new javax.swing.GroupLayout(pnlTituloAltExcClientes);
        pnlTituloAltExcClientes.setLayout(pnlTituloAltExcClientesLayout);
        pnlTituloAltExcClientesLayout.setHorizontalGroup(
            pnlTituloAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAltExcClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloAltExcClientes)
                .addGap(201, 201, 201))
        );
        pnlTituloAltExcClientesLayout.setVerticalGroup(
            pnlTituloAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAltExcClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAltExcClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAlterarClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnAlterarClientes.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnAlterarClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterarClientes.setText("Alterar");
        btnAlterarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClientesActionPerformed(evt);
            }
        });

        btnExcluirClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnExcluirClientes.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnExcluirClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirClientes.setText("Excluir");

        tblAltExcClientes.setBackground(new java.awt.Color(0, 0, 0));
        tblAltExcClientes.setForeground(new java.awt.Color(204, 255, 204));
        tblAltExcClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "CPF", "Nome", "E-mail", "DataNasc", "Telefone", "Sexo", "CEP", "Logradouro", "Numero", "Cidade", "Complemento", "Estado Civil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAltExcClientes.setToolTipText("");
        tblAltExcClientes.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblAltExcClientes);

        lblNomeConsCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblNomeConsCli.setForeground(new java.awt.Color(204, 255, 204));
        lblNomeConsCli.setText("CPF:");

        pnlInfoConsClientes.setBackground(new java.awt.Color(0, 0, 0));

        txtAltExcCidCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcCidCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcCidCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcCidCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcTelCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcTelCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcTelCli.setText("Telefone:");

        lblAltExcCepCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcCepCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCepCli.setText("CEP:");

        lblAltExcLograCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcLograCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcLograCli.setText("Logradouro:");

        lblAltExcSexCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcSexCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcSexCli.setText("Sexo:");

        txtAltExcNumCepCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcNumCepCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcNumCepCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcNumCepCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcIdCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcIdCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcIdCli.setText("ID:");

        lblAltExcNomeCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcNomeCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcNomeCli.setText("Nome:");

        txtAltExcCepCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcCepCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcCepCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcCepCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcCepCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblAltExcComplCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcComplCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcComplCli.setText("Complemento:");

        txtAltExcEmailCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcEmailCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcEmailCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcEmailCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcEmailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltExcEmailCliActionPerformed(evt);
            }
        });

        lblAltExcNumCepCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcNumCepCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcNumCepCli.setText("Numero:");

        txtAltExcComplCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcComplCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcComplCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcComplCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcECCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcECCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcECCli.setText("Estado Civil:");

        txtAltExcLograCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcLograCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcLograCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcLograCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcCidCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcCidCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCidCli.setText("Cidade:");

        txtAltExcTelCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcTelCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcTelCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcTelCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcTelCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblAltExcCpfCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcCpfCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCpfCli.setText("CPF:");

        lblAltExcDataNascCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcDataNascCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcDataNascCli.setText("Data de Nascimento:");

        txtAltExcNomeCli.setBackground(new java.awt.Color(255, 255, 255));
        txtAltExcNomeCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcNomeCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcNomeCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcEmailCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcEmailCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcEmailCli.setText("E-mail:");

        lblAltExcIdCliAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAltExcIdCliAt.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcIdCliAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltExcIdCliAt.setText("______");

        lblAltExcCpfCliAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAltExcCpfCliAt.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCpfCliAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltExcCpfCliAt.setText("______");

        lblAltExcDataNasCliAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAltExcDataNasCliAt.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcDataNasCliAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltExcDataNasCliAt.setText("______");

        cbbAltExcSexoCliAt.setBackground(new java.awt.Color(255, 255, 255));
        cbbAltExcSexoCliAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbbAltExcSexoCliAt.setForeground(new java.awt.Color(0, 0, 0));
        cbbAltExcSexoCliAt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbbAltExcSexoCliAt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        cbbAltExcEstCivCliAt.setBackground(new java.awt.Color(255, 255, 255));
        cbbAltExcEstCivCliAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbbAltExcEstCivCliAt.setForeground(new java.awt.Color(0, 0, 0));
        cbbAltExcEstCivCliAt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..", "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)", "União Estável" }));
        cbbAltExcEstCivCliAt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        javax.swing.GroupLayout pnlInfoConsClientesLayout = new javax.swing.GroupLayout(pnlInfoConsClientes);
        pnlInfoConsClientes.setLayout(pnlInfoConsClientesLayout);
        pnlInfoConsClientesLayout.setHorizontalGroup(
            pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                        .addComponent(lblAltExcEmailCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAltExcEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblAltExcECCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbAltExcEstCivCliAt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                        .addComponent(lblAltExcComplCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAltExcComplCli, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                            .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAltExcDataNascCli)
                                .addComponent(lblAltExcNomeCli))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                                    .addComponent(lblAltExcDataNasCliAt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(315, 315, 315)
                                    .addComponent(lblAltExcSexCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbAltExcSexoCliAt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtAltExcNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                            .addComponent(lblAltExcLograCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcLograCli, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInfoConsClientesLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(lblAltExcIdCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblAltExcIdCliAt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAltExcCpfCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblAltExcCpfCliAt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                            .addComponent(lblAltExcCepCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98)
                            .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                                    .addComponent(lblAltExcCidCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAltExcCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                                    .addComponent(lblAltExcTelCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAltExcTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(69, 69, 69)
                            .addComponent(lblAltExcNumCepCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcNumCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlInfoConsClientesLayout.setVerticalGroup(
            pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcIdCli)
                    .addComponent(lblAltExcCpfCli)
                    .addComponent(lblAltExcIdCliAt)
                    .addComponent(lblAltExcCpfCliAt))
                .addGap(35, 35, 35)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcNomeCli)
                    .addComponent(txtAltExcNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcDataNascCli)
                    .addComponent(lblAltExcTelCli)
                    .addComponent(txtAltExcTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcSexCli)
                    .addComponent(lblAltExcDataNasCliAt)
                    .addComponent(cbbAltExcSexoCliAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcNumCepCli)
                    .addComponent(txtAltExcNumCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcCidCli)
                    .addComponent(txtAltExcCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcCepCli)
                    .addComponent(txtAltExcCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcLograCli)
                    .addComponent(txtAltExcLograCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcComplCli)
                    .addComponent(txtAltExcComplCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltExcEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcEmailCli)
                    .addComponent(lblAltExcECCli)
                    .addComponent(cbbAltExcEstCivCliAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlInfoConsClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAltExcCepCli, txtAltExcComplCli, txtAltExcEmailCli, txtAltExcLograCli, txtAltExcNomeCli, txtAltExcNumCepCli, txtAltExcTelCli});

        lblInfoAltExcClientes.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblInfoAltExcClientes.setForeground(new java.awt.Color(204, 255, 204));
        lblInfoAltExcClientes.setText("Informe o ID ou o nome para consulta");

        btnConsutarClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnConsutarClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnConsutarClientes.setText("Consultar");
        btnConsutarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsutarClientesActionPerformed(evt);
            }
        });

        txtCpfCliCons.setBackground(new java.awt.Color(255, 255, 255));
        txtCpfCliCons.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtCpfCliCons.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpfCliCons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliCons.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlPrincipalAltExcClientesLayout = new javax.swing.GroupLayout(pnlPrincipalAltExcClientes);
        pnlPrincipalAltExcClientes.setLayout(pnlPrincipalAltExcClientesLayout);
        pnlPrincipalAltExcClientesLayout.setHorizontalGroup(
            pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloAltExcClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInfoAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btnAlterarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnExcluirClientes))
                    .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblNomeConsCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpfCliCons, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(btnConsutarClientes))
                    .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(pnlInfoConsClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pnlPrincipalAltExcClientesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterarClientes, btnExcluirClientes});

        pnlPrincipalAltExcClientesLayout.setVerticalGroup(
            pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                .addComponent(pnlTituloAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInfoAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeConsCli)
                    .addComponent(btnConsutarClientes)
                    .addComponent(txtCpfCliCons, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInfoConsClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirClientes))
                .addGap(35, 35, 35))
        );

        pnlPrincipalAltExcClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterarClientes, btnExcluirClientes});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAltExcEmailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltExcEmailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltExcEmailCliActionPerformed

    private void btnConsutarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutarClientesActionPerformed
        Validador validacao = new Validador();
        
        validacao.ValidarCpf(txtCpfCliCons);
        
        if(validacao.hasErro()){
            JOptionPane.showMessageDialog(this, "Informe o CPF para consulta");
        }
    }//GEN-LAST:event_btnConsutarClientesActionPerformed

    private void btnAlterarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClientesActionPerformed
        Validador validacao = new Validador();
        
        validacao.ValidarTextos(txtAltExcNomeCli);
        validacao.ValidarTelefone(txtAltExcTelCli);
        validacao.ValidarComboBox(cbbAltExcSexoCliAt);
        validacao.ValidarCep(txtAltExcCepCli);
        validacao.ValidarTextos(txtAltExcCidCli);
        validacao.ValidarNumero(txtAltExcNumCepCli);
        validacao.ValidarTextos(txtAltExcLograCli);
        validacao.ValidarTextos(txtAltExcEmailCli);
        
        if(validacao.hasErro()){
            JOptionPane.showMessageDialog(this, "Preencha corretamente os campos em vermelho!");
        }
    }//GEN-LAST:event_btnAlterarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlteExclClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarClientes;
    private javax.swing.JButton btnConsutarClientes;
    private javax.swing.JButton btnExcluirClientes;
    private javax.swing.JComboBox<String> cbbAltExcEstCivCliAt;
    private javax.swing.JComboBox<String> cbbAltExcSexoCliAt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltExcCepCli;
    private javax.swing.JLabel lblAltExcCidCli;
    private javax.swing.JLabel lblAltExcComplCli;
    private javax.swing.JLabel lblAltExcCpfCli;
    private javax.swing.JLabel lblAltExcCpfCliAt;
    private javax.swing.JLabel lblAltExcDataNasCliAt;
    private javax.swing.JLabel lblAltExcDataNascCli;
    private javax.swing.JLabel lblAltExcECCli;
    private javax.swing.JLabel lblAltExcEmailCli;
    private javax.swing.JLabel lblAltExcIdCli;
    private javax.swing.JLabel lblAltExcIdCliAt;
    private javax.swing.JLabel lblAltExcLograCli;
    private javax.swing.JLabel lblAltExcNomeCli;
    private javax.swing.JLabel lblAltExcNumCepCli;
    private javax.swing.JLabel lblAltExcSexCli;
    private javax.swing.JLabel lblAltExcTelCli;
    private javax.swing.JLabel lblInfoAltExcClientes;
    private javax.swing.JLabel lblNomeConsCli;
    private javax.swing.JLabel lblTituloAltExcClientes;
    private javax.swing.JPanel pnlInfoConsClientes;
    private javax.swing.JPanel pnlPrincipalAltExcClientes;
    private javax.swing.JPanel pnlTituloAltExcClientes;
    private javax.swing.JTable tblAltExcClientes;
    private javax.swing.JFormattedTextField txtAltExcCepCli;
    private javax.swing.JTextField txtAltExcCidCli;
    private javax.swing.JTextField txtAltExcComplCli;
    private javax.swing.JTextField txtAltExcEmailCli;
    private javax.swing.JTextField txtAltExcLograCli;
    private javax.swing.JTextField txtAltExcNomeCli;
    private javax.swing.JTextField txtAltExcNumCepCli;
    private javax.swing.JFormattedTextField txtAltExcTelCli;
    private javax.swing.JFormattedTextField txtCpfCliCons;
    // End of variables declaration//GEN-END:variables
}
