/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import utils.Validador;

/**
 *
 * @author caueg
 */
public class TelaAlteExclProdutosView extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroClientesView
     */
    public TelaAlteExclProdutosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalAltExcProdut = new javax.swing.JPanel();
        pnlTituloAltExcProdutos = new javax.swing.JPanel();
        lblTituloAltExcProdutos = new javax.swing.JLabel();
        btnAlterarProdutos = new javax.swing.JButton();
        btnExcluirProdut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAltExcProdutos = new javax.swing.JTable();
        lblInfoAltExcProdutos = new javax.swing.JLabel();
        pnlItensProd = new javax.swing.JPanel();
        lblTamanProd = new javax.swing.JLabel();
        lblModalidade = new javax.swing.JLabel();
        txtPrecoProd = new javax.swing.JTextField();
        lblCorProd = new javax.swing.JLabel();
        lblIModeloProd = new javax.swing.JLabel();
        lblQuantProdVend = new javax.swing.JLabel();
        lblMarcaProd = new javax.swing.JLabel();
        lblMarcaProdAt = new javax.swing.JLabel();
        lblModalidProdAt = new javax.swing.JLabel();
        lblCorProdAt = new javax.swing.JLabel();
        lblTamanProdAt1 = new javax.swing.JLabel();
        lblTamanProdAt2 = new javax.swing.JLabel();
        pnlConsultaProd = new javax.swing.JPanel();
        lblIdConsProd = new javax.swing.JLabel();
        txtIdConsProd = new javax.swing.JTextField();
        btnConsutarProdutos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Alteração e Exclusão de Clientes");
        setAlwaysOnTop(true);

        pnlPrincipalAltExcProdut.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalAltExcProdut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloAltExcProdutos.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloAltExcProdutos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloAltExcProdutos.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloAltExcProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAltExcProdutos.setText("Alteração e Exclusão de Produtos");

        javax.swing.GroupLayout pnlTituloAltExcProdutosLayout = new javax.swing.GroupLayout(pnlTituloAltExcProdutos);
        pnlTituloAltExcProdutos.setLayout(pnlTituloAltExcProdutosLayout);
        pnlTituloAltExcProdutosLayout.setHorizontalGroup(
            pnlTituloAltExcProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAltExcProdutosLayout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(lblTituloAltExcProdutos)
                .addGap(201, 201, 201))
        );
        pnlTituloAltExcProdutosLayout.setVerticalGroup(
            pnlTituloAltExcProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAltExcProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAltExcProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAlterarProdutos.setBackground(new java.awt.Color(204, 255, 204));
        btnAlterarProdutos.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnAlterarProdutos.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterarProdutos.setText("Alterar");
        btnAlterarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutosActionPerformed(evt);
            }
        });

        btnExcluirProdut.setBackground(new java.awt.Color(204, 255, 204));
        btnExcluirProdut.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnExcluirProdut.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirProdut.setText("Excluir");

        tblAltExcProdutos.setBackground(new java.awt.Color(0, 0, 0));
        tblAltExcProdutos.setForeground(new java.awt.Color(204, 255, 204));
        tblAltExcProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Modelo", "Modalidade", "Preço", "Cor", "Tamanho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAltExcProdutos.setToolTipText("");
        tblAltExcProdutos.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblAltExcProdutos);

        lblInfoAltExcProdutos.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblInfoAltExcProdutos.setForeground(new java.awt.Color(204, 255, 204));
        lblInfoAltExcProdutos.setText("Informe o ID do produto para consulta");

        pnlItensProd.setBackground(new java.awt.Color(0, 0, 0));

        lblTamanProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblTamanProd.setForeground(new java.awt.Color(204, 255, 204));
        lblTamanProd.setText("Tamanho:");

        lblModalidade.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblModalidade.setForeground(new java.awt.Color(204, 255, 204));
        lblModalidade.setText("Modalidade:");

        txtPrecoProd.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecoProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPrecoProd.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecoProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblCorProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblCorProd.setForeground(new java.awt.Color(204, 255, 204));
        lblCorProd.setText("Cor:");

        lblIModeloProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblIModeloProd.setForeground(new java.awt.Color(204, 255, 204));
        lblIModeloProd.setText("Modelo:");

        lblQuantProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblQuantProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblQuantProdVend.setText("Preço:");

        lblMarcaProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblMarcaProd.setForeground(new java.awt.Color(204, 255, 204));
        lblMarcaProd.setText("Marca:");

        lblMarcaProdAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMarcaProdAt.setForeground(new java.awt.Color(204, 255, 204));
        lblMarcaProdAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarcaProdAt.setText("_______");

        lblModalidProdAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblModalidProdAt.setForeground(new java.awt.Color(204, 255, 204));
        lblModalidProdAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModalidProdAt.setText("_______");

        lblCorProdAt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorProdAt.setForeground(new java.awt.Color(204, 255, 204));
        lblCorProdAt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorProdAt.setText("_______");

        lblTamanProdAt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTamanProdAt1.setForeground(new java.awt.Color(204, 255, 204));
        lblTamanProdAt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamanProdAt1.setText("_______");

        lblTamanProdAt2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTamanProdAt2.setForeground(new java.awt.Color(204, 255, 204));
        lblTamanProdAt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamanProdAt2.setText("_______");

        javax.swing.GroupLayout pnlItensProdLayout = new javax.swing.GroupLayout(pnlItensProd);
        pnlItensProd.setLayout(pnlItensProdLayout);
        pnlItensProdLayout.setHorizontalGroup(
            pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addComponent(lblModalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModalidProdAt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addComponent(lblMarcaProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMarcaProdAt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addComponent(lblCorProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorProdAt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)))
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIModeloProd)
                    .addComponent(lblTamanProd)
                    .addComponent(lblQuantProdVend))
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTamanProdAt1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTamanProdAt2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlItensProdLayout.setVerticalGroup(
            pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensProdLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaProd)
                    .addComponent(lblIModeloProd)
                    .addComponent(lblMarcaProdAt)
                    .addComponent(lblTamanProdAt2))
                .addGap(40, 40, 40)
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModalidade)
                    .addComponent(txtPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantProdVend)
                    .addComponent(lblModalidProdAt))
                .addGap(35, 35, 35)
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanProd)
                    .addComponent(lblCorProd)
                    .addComponent(lblCorProdAt)
                    .addComponent(lblTamanProdAt1))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pnlConsultaProd.setBackground(new java.awt.Color(0, 0, 0));

        lblIdConsProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdConsProd.setForeground(new java.awt.Color(204, 255, 204));
        lblIdConsProd.setText("ID:");

        txtIdConsProd.setBackground(new java.awt.Color(255, 255, 255));
        txtIdConsProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdConsProd.setForeground(new java.awt.Color(0, 0, 0));
        txtIdConsProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        btnConsutarProdutos.setBackground(new java.awt.Color(204, 255, 204));
        btnConsutarProdutos.setForeground(new java.awt.Color(0, 0, 0));
        btnConsutarProdutos.setText("Consultar");
        btnConsutarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsutarProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultaProdLayout = new javax.swing.GroupLayout(pnlConsultaProd);
        pnlConsultaProd.setLayout(pnlConsultaProdLayout);
        pnlConsultaProdLayout.setHorizontalGroup(
            pnlConsultaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaProdLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(lblIdConsProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdConsProd, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(btnConsutarProdutos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultaProdLayout.setVerticalGroup(
            pnlConsultaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdConsProd)
                    .addComponent(txtIdConsProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsutarProdutos))
                .addContainerGap())
        );

        pnlConsultaProdLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsutarProdutos, txtIdConsProd});

        javax.swing.GroupLayout pnlPrincipalAltExcProdutLayout = new javax.swing.GroupLayout(pnlPrincipalAltExcProdut);
        pnlPrincipalAltExcProdut.setLayout(pnlPrincipalAltExcProdutLayout);
        pnlPrincipalAltExcProdutLayout.setHorizontalGroup(
            pnlPrincipalAltExcProdutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloAltExcProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalAltExcProdutLayout.createSequentialGroup()
                .addGroup(pnlPrincipalAltExcProdutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalAltExcProdutLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btnAlterarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnExcluirProdut)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalAltExcProdutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPrincipalAltExcProdutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalAltExcProdutLayout.createSequentialGroup()
                                .addComponent(pnlConsultaProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))))
                    .addGroup(pnlPrincipalAltExcProdutLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(pnlItensProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlPrincipalAltExcProdutLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(lblInfoAltExcProdutos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrincipalAltExcProdutLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterarProdutos, btnExcluirProdut});

        pnlPrincipalAltExcProdutLayout.setVerticalGroup(
            pnlPrincipalAltExcProdutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalAltExcProdutLayout.createSequentialGroup()
                .addComponent(pnlTituloAltExcProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInfoAltExcProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlConsultaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlItensProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlPrincipalAltExcProdutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirProdut))
                .addGap(35, 35, 35))
        );

        pnlPrincipalAltExcProdutLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterarProdutos, btnExcluirProdut});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcProdut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcProdut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsutarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutarProdutosActionPerformed
        Validador validacao = new Validador();
        
        validacao.ValidarNumero(txtIdConsProd);
        
        if(validacao.hasErro()){
            JOptionPane.showMessageDialog(this, "Preencha corretamento os campos em vermelho");
        }
    }//GEN-LAST:event_btnConsutarProdutosActionPerformed

    private void btnAlterarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutosActionPerformed
        Validador validacao = new Validador();
        
        validacao.ValidarDouble(txtPrecoProd);
        
        if(validacao.hasErro()){
            JOptionPane.showMessageDialog(this, "Preencha o campo que desseja alterar");
        }
    }//GEN-LAST:event_btnAlterarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlteExclProdutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarProdutos;
    private javax.swing.JButton btnConsutarProdutos;
    private javax.swing.JButton btnExcluirProdut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorProd;
    private javax.swing.JLabel lblCorProdAt;
    private javax.swing.JLabel lblIModeloProd;
    private javax.swing.JLabel lblIdConsProd;
    private javax.swing.JLabel lblInfoAltExcProdutos;
    private javax.swing.JLabel lblMarcaProd;
    private javax.swing.JLabel lblMarcaProdAt;
    private javax.swing.JLabel lblModalidProdAt;
    private javax.swing.JLabel lblModalidade;
    private javax.swing.JLabel lblQuantProdVend;
    private javax.swing.JLabel lblTamanProd;
    private javax.swing.JLabel lblTamanProdAt1;
    private javax.swing.JLabel lblTamanProdAt2;
    private javax.swing.JLabel lblTituloAltExcProdutos;
    private javax.swing.JPanel pnlConsultaProd;
    private javax.swing.JPanel pnlItensProd;
    private javax.swing.JPanel pnlPrincipalAltExcProdut;
    private javax.swing.JPanel pnlTituloAltExcProdutos;
    private javax.swing.JTable tblAltExcProdutos;
    private javax.swing.JTextField txtIdConsProd;
    private javax.swing.JTextField txtPrecoProd;
    // End of variables declaration//GEN-END:variables
}
