/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import utils.Validador;

/**
 *
 * @author caueg
 */
public class TelaEstoqueProdView extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstoqueProdView
     */
    public TelaEstoqueProdView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalTelaEst = new javax.swing.JPanel();
        pnlTituloTela = new javax.swing.JPanel();
        lblTituloDeTela = new javax.swing.JLabel();
        pnlIdProd = new javax.swing.JPanel();
        lblIdProd = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        pnlQuantAcres = new javax.swing.JPanel();
        txtQuantAcres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipalTelaEst.setBackground(new java.awt.Color(0, 0, 0));

        pnlTituloTela.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloDeTela.setBackground(new java.awt.Color(0, 0, 0));
        lblTituloDeTela.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloDeTela.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloDeTela.setText("Estoque de produtos");

        javax.swing.GroupLayout pnlTituloTelaLayout = new javax.swing.GroupLayout(pnlTituloTela);
        pnlTituloTela.setLayout(pnlTituloTelaLayout);
        pnlTituloTelaLayout.setHorizontalGroup(
            pnlTituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloTelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloDeTela)
                .addGap(79, 79, 79))
        );
        pnlTituloTelaLayout.setVerticalGroup(
            pnlTituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTelaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTituloDeTela)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlIdProd.setBackground(new java.awt.Color(0, 0, 0));
        pnlIdProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblIdProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        lblIdProd.setForeground(new java.awt.Color(204, 255, 204));
        lblIdProd.setText("* ID do Produto:");

        txtIdProd.setBackground(new java.awt.Color(255, 255, 255));
        txtIdProd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtIdProd.setForeground(new java.awt.Color(0, 0, 0));
        txtIdProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        javax.swing.GroupLayout pnlIdProdLayout = new javax.swing.GroupLayout(pnlIdProd);
        pnlIdProd.setLayout(pnlIdProdLayout);
        pnlIdProdLayout.setHorizontalGroup(
            pnlIdProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlIdProdLayout.setVerticalGroup(
            pnlIdProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdProdLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlIdProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProd)
                    .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlQuantAcres.setBackground(new java.awt.Color(0, 0, 0));
        pnlQuantAcres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtQuantAcres.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantAcres.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtQuantAcres.setForeground(new java.awt.Color(0, 0, 0));
        txtQuantAcres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantAcres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("acrescentar ou remover");

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Informe o valor que deseja");

        javax.swing.GroupLayout pnlQuantAcresLayout = new javax.swing.GroupLayout(pnlQuantAcres);
        pnlQuantAcres.setLayout(pnlQuantAcresLayout);
        pnlQuantAcresLayout.setHorizontalGroup(
            pnlQuantAcresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuantAcresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlQuantAcresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuantAcresLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuantAcresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtQuantAcres, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        pnlQuantAcresLayout.setVerticalGroup(
            pnlQuantAcresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuantAcresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(txtQuantAcres, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnSalvar.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Acrescentar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSalvar1.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalvar1.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar1.setText("Remover");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalTelaEstLayout = new javax.swing.GroupLayout(pnlPrincipalTelaEst);
        pnlPrincipalTelaEst.setLayout(pnlPrincipalTelaEstLayout);
        pnlPrincipalTelaEstLayout.setHorizontalGroup(
            pnlPrincipalTelaEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalTelaEstLayout.createSequentialGroup()
                .addGroup(pnlPrincipalTelaEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalTelaEstLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalTelaEstLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalTelaEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalTelaEstLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalTelaEstLayout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(pnlQuantAcres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalTelaEstLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        pnlPrincipalTelaEstLayout.setVerticalGroup(
            pnlPrincipalTelaEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalTelaEstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(pnlIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(pnlQuantAcres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(pnlPrincipalTelaEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        pnlPrincipalTelaEstLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSalvar, btnSalvar1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalTelaEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalTelaEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Validador validacao = new Validador();

        validacao.ValidarNumero(txtIdProd);
        validacao.ValidarNumero(txtQuantAcres);
        
        if(validacao.hasErro()){
            JOptionPane.showMessageDialog(this, "Informe um valor para os campos em vermelho");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        Validador validacao = new Validador();

        validacao.ValidarNumero(txtIdProd);
        validacao.ValidarNumero(txtQuantAcres);
        
        if(validacao.hasErro()){
            JOptionPane.showMessageDialog(this, "Informe um valor para os campos em vermelho");
        }
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueProdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueProdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueProdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueProdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoqueProdView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIdProd;
    private javax.swing.JLabel lblTituloDeTela;
    private javax.swing.JPanel pnlIdProd;
    private javax.swing.JPanel pnlPrincipalTelaEst;
    private javax.swing.JPanel pnlQuantAcres;
    private javax.swing.JPanel pnlTituloTela;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtQuantAcres;
    // End of variables declaration//GEN-END:variables
}
